["protostar.config"]
protostar_version = "0.2.5"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src", "src"]

[profile.ci.protostar.shared_command_configs]
no_color=true

["protostar.contracts"]
stiki = [
    "src/contracts/stiki.cairo",
]
